import type { Metadata } from "next";
import "./styles/globals.css";
// Components
import Header from "./components/Header";
import Footer from "./components/Footer";
// Google fonts
import { Noto_Serif_JP } from "next/font/google";
const notoSerifJp = Noto_Serif_JP({
  subsets: ["latin"],
  weight: ["400", "700"],
});

// Head
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ja" className={notoSerifJp.className}>
      <body>
        <Header />
        {children}
        <Footer />
      </body>
    </html>
  );
}
